# Generated by Django 3.1.1 on 2020-11-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('Matricula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPatern', models.CharField(max_length=35)),
                ('apellidoMatern', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('estatus', models.CharField(choices=[('1', 'Aspirante'), ('2', 'Estudiante'), ('3', 'Egresado')], default='Aspirante', max_length=10)),
            ],
        ),
    ]
