# Generated by Django 3.1.1 on 2020-12-16 02:16

import Egresados.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='email')),
                ('matricula', models.IntegerField(unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=65, unique=True)),
                ('last_name', models.CharField(max_length=60)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=Egresados.models.get_default_profile_image, null=True, upload_to=Egresados.models.get_profile_image_filepath)),
                ('hide_email', models.BooleanField(default=True)),
                ('estatus', models.CharField(choices=[('1', 'Aspirante'), ('2', 'Estudiante'), ('3', 'Egresado'), ('4', 'Administrativos'), ('5', 'Investigador'), ('6', 'Administrador')], default='Aspirante', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMateria', models.CharField(default='any', max_length=50)),
                ('tutorMateria', models.CharField(default='any', max_length=50)),
                ('califs', models.IntegerField(default=70)),
                ('fechaCalifs', models.DateTimeField(blank=True, null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCurso', models.CharField(default='any', max_length=50)),
                ('tutorCurso', models.CharField(default='any', max_length=50)),
                ('fechaCurso', models.DateTimeField(auto_now=True, null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
