# Generated by Django 3.1.1 on 2020-11-17 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Egresados', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
