# Generated by Django 3.1.1 on 2020-12-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Egresados', '0002_auto_20201215_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuarios',
            name='matricula',
            field=models.IntegerField(null=True, unique=True, verbose_name='Matricula'),
        ),
    ]
