# Generated by Django 3.1.1 on 2020-12-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Egresados', '0003_auto_20201215_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusuarios',
            old_name='last_name',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='customusuarios',
            old_name='username',
            new_name='nombre',
        ),
    ]
