# Generated by Django 3.1.1 on 2020-12-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Egresados', '0004_auto_20201217_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuarios',
            name='estatus',
            field=models.CharField(choices=[('1', 'Aspirante'), ('2', 'Estudiante'), ('3', 'Egresado'), ('4', 'Administrativos'), ('5', 'Investigador'), ('6', 'Administrador')], default='Estudiante', max_length=20),
        ),
    ]
