# Generated by Django 3.1.1 on 2021-01-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Egresados', '0005_auto_20201230_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='users',
            field=models.ManyToManyField(to='Egresados.CustomUsuarios'),
        ),
        migrations.AlterField(
            model_name='materias',
            name='users',
            field=models.ManyToManyField(to='Egresados.CustomUsuarios'),
        ),
    ]
