# Generated by Django 3.1.1 on 2020-12-30 06:22

import GestionAcademicaWebApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademicaWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='E-mail')),
                ('matricula', models.IntegerField(null=True, unique=True, verbose_name='Matricula')),
                ('nombre', models.CharField(max_length=65, unique=True)),
                ('apellidos', models.CharField(max_length=60)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=GestionAcademicaWebApp.models.get_default_profile_image, null=True, upload_to=GestionAcademicaWebApp.models.get_profile_image_filepath)),
                ('hide_email', models.BooleanField(default=True)),
                ('estatus', models.CharField(choices=[('1', 'Aspirante'), ('2', 'Estudiante'), ('3', 'Egresado'), ('4', 'Administrativos'), ('5', 'Investigador'), ('6', 'Administrador')], default='Estudiante', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AddField(
            model_name='cursos',
            name='users',
            field=models.ManyToManyField(to='GestionAcademicaWebApp.CustomUsuarios'),
        ),
        migrations.AddField(
            model_name='materias',
            name='users',
            field=models.ManyToManyField(to='GestionAcademicaWebApp.CustomUsuarios'),
        ),
    ]
