# Generated by Django 3.1.1 on 2020-11-09 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademicaWebApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
