# Generated by Django 3.1.1 on 2020-11-17 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionAcademicaWebApp', '0002_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('idCurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCurso', models.CharField(max_length=50)),
                ('tutorCurso', models.CharField(max_length=50)),
                ('fechaCurso', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('idMateria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMateria', models.CharField(max_length=50)),
                ('tutorMateria', models.CharField(max_length=50)),
                ('califs', models.IntegerField()),
                ('fechaCalifs', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('IdUser', models.AutoField(primary_key=True, serialize=False)),
                ('Matricula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('estatus', models.CharField(choices=[('1', 'Aspirante'), ('2', 'Estudiante'), ('3', 'Egresado'), ('4', 'Administrativos'), ('5', 'Investigador'), ('6', 'Administrador')], default='Aspirante', max_length=20)),
                ('cursos', models.ManyToManyField(to='GestionAcademicaWebApp.Cursos')),
                ('materias', models.ManyToManyField(to='GestionAcademicaWebApp.Materias')),
            ],
        ),
    ]
