# Generated by Django 3.1.1 on 2021-01-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademicaWebApp', '0002_auto_20201230_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuarios',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='E-Mail'),
        ),
    ]
