# Generated by Django 3.1.1 on 2020-12-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademicaWebApp', '0003_cursos_materias_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='idCurso',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='idMateria',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='IdUser',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='password',
        ),
        migrations.AddField(
            model_name='cursos',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materias',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Apellidos',
            field=models.CharField(default='any', max_length=65),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Email',
            field=models.CharField(default='any', max_length=50),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='Nombre',
            field=models.CharField(default='any', max_length=40),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cursos',
            name='fechaCurso',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nombreCurso',
            field=models.CharField(default='any', max_length=50),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='tutorCurso',
            field=models.CharField(default='any', max_length=50),
        ),
        migrations.AlterField(
            model_name='materias',
            name='califs',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='materias',
            name='fechaCalifs',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materias',
            name='nombreMateria',
            field=models.CharField(default='any', max_length=50),
        ),
        migrations.AlterField(
            model_name='materias',
            name='tutorMateria',
            field=models.CharField(default='any', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Matricula',
            field=models.CharField(default='any', max_length=10),
        ),
    ]
